"""Declarative DataFrame contracts published with the hms2cng documentation."""

SCHEMA_VERSION = "1.0"

DATAFRAME_SCHEMAS = {
    "merged_geometry": {
        "description": "HEC-HMS geometry layers returned by merge_all_layers(), distinguished by layer.",
        "accessor": "hms2cng.merge_all_layers(...) or the consolidated archive GeoParquet",
        "source": "hms2cng.geometry.merge_all_layers",
        "extra_columns": True,
        "dynamic": True,
        "columns": [
            {"name": "layer", "dtype": "str", "description": "Geometry layer discriminator."},
            {"name": "geometry", "dtype": "GeoSeries", "description": "Layer geometry."},
        ],
    },
    "results_summary": {
        "description": "Per-element HEC-HMS summary statistics parsed from a RUN results XML file.",
        "accessor": "hms2cng.results.parse_results_xml(...) or merge_all_variables(...) rows",
        "source": "hms2cng.results.parse_results_xml",
        "extra_columns": False,
        "dynamic": False,
        "columns": [
            {"name": "name", "dtype": "str", "description": "HMS element name."},
            {"name": "element_type", "dtype": "str", "description": "HMS element type."},
            {"name": "run_name", "dtype": "str | None", "description": "Simulation run name."},
            {"name": "variable_prefix", "dtype": "str", "description": "Resolved HMS statistic prefix."},
            {"name": "max_value", "dtype": "float", "description": "Maximum value."},
            {"name": "time_of_max", "dtype": "datetime | None", "description": "Time of maximum value."},
            {"name": "min_value", "dtype": "float", "description": "Minimum value."},
            {"name": "time_of_min", "dtype": "datetime | None", "description": "Time of minimum value."},
            {"name": "mean_value", "dtype": "float", "description": "Average value."},
            {"name": "volume", "dtype": "float", "description": "Reported volume, when present."},
            {"name": "depth", "dtype": "float", "description": "Reported depth, when present."},
            {"name": "units", "dtype": "str | None", "description": "Statistic units."},
        ],
    },
    "project_manifest": {
        "description": "Single-row project summary written to manifest.parquet.",
        "accessor": "hms2cng.get_project_manifest(...) or export_project_manifest(...) output",
        "source": "hms2cng.project.get_project_manifest",
        "extra_columns": False,
        "dynamic": False,
        "columns": [
            {"name": "project_name", "dtype": "str", "description": "HEC-HMS project name."},
            {"name": "project_file", "dtype": "str", "description": "Path to the .hms file."},
            {"name": "hms_version", "dtype": "str | None", "description": "HEC-HMS version."},
            {"name": "crs_epsg", "dtype": "str | None", "description": "Detected project CRS."},
            {"name": "is_gridded", "dtype": "bool", "description": "Whether the project is gridded."},
            {"name": "num_basin_models", "dtype": "int", "description": "Basin-model count."},
            {"name": "num_met_models", "dtype": "int", "description": "Meteorologic-model count."},
            {"name": "num_control_specs", "dtype": "int", "description": "Control-specification count."},
            {"name": "num_runs", "dtype": "int", "description": "Simulation-run count."},
            {"name": "basin_models", "dtype": "JSON str", "description": "Basin-model names."},
            {"name": "met_models", "dtype": "JSON str", "description": "Meteorologic-model names."},
            {"name": "run_names", "dtype": "JSON str", "description": "Simulation-run names."},
            {"name": "export_timestamp", "dtype": "ISO 8601 str", "description": "UTC export time."},
        ],
    },
    "run_registry": {
        "description": "One row per HEC-HMS simulation run with model lineage and results availability.",
        "accessor": "export_project_manifest(...) output run_registry.parquet",
        "source": "hms2cng.project.export_project_manifest",
        "extra_columns": False,
        "dynamic": False,
        "columns": [
            {"name": "project_name", "dtype": "str", "description": "HEC-HMS project name."},
            {"name": "run_name", "dtype": "str", "description": "Simulation-run name."},
            {"name": "run_slug", "dtype": "str", "description": "Filesystem-safe run identifier."},
            {"name": "basin_model", "dtype": "str", "description": "Linked basin model."},
            {"name": "met_model", "dtype": "str", "description": "Linked meteorologic model."},
            {"name": "control_spec", "dtype": "str", "description": "Linked control specification."},
            {"name": "start_date", "dtype": "datetime | None", "description": "Control-window start."},
            {"name": "end_date", "dtype": "datetime | None", "description": "Control-window end."},
            {"name": "time_interval_minutes", "dtype": "float | None", "description": "Simulation interval."},
            {"name": "duration_hours", "dtype": "float | None", "description": "Simulation duration."},
            {"name": "last_execution_date", "dtype": "str | None", "description": "Last execution date."},
            {"name": "last_execution_time", "dtype": "str | None", "description": "Last execution time."},
            {"name": "results_file", "dtype": "str | None", "description": "Resolved results XML path."},
            {"name": "has_results", "dtype": "bool", "description": "Whether a results XML was found."},
        ],
    },
    "duckdb_query_results": {
        "description": "Arbitrary tabular result returned by query_parquet() or DuckSession.query().",
        "accessor": "hms2cng.query_parquet(path, sql)",
        "source": "hms2cng.duckdb_session.query_parquet",
        "extra_columns": True,
        "dynamic": True,
        "columns": [],
    },
}
